import { mapping } from "file-mapping";

export const progress = mapping("progress.json", {} as Record<string, Record<string, number>>);
export const scoreboard = mapping("scoreboard.json", {
    第一小隊: {
        "T.E.S.T.": 0,
        深入敵營: 0,
        無名小鎮的無解之謎: 0,
        "ㄕㄜˊ不ㄕㄜ`": 0,
        反目成仇: 0,
        AlGoBang: 0,
        "Modern Web": 0,
    },
    第二小隊: {
        "T.E.S.T.": 0,
        深入敵營: 0,
        無名小鎮的無解之謎: 0,
        "ㄕㄜˊ不ㄕㄜ`": 0,
        反目成仇: 0,
        AlGoBang: 0,
        "Modern Web": 0,
    },
    第三小隊: {
        "T.E.S.T.": 0,
        深入敵營: 0,
        無名小鎮的無解之謎: 0,
        "ㄕㄜˊ不ㄕㄜ`": 0,
        反目成仇: 0,
        AlGoBang: 0,
        "Modern Web": 0,
    },
    第四小隊: {
        "T.E.S.T.": 0,
        深入敵營: 0,
        無名小鎮的無解之謎: 0,
        "ㄕㄜˊ不ㄕㄜ`": 0,
        反目成仇: 0,
        AlGoBang: 0,
        "Modern Web": 0,
    },
    第五小隊: {
        "T.E.S.T.": 0,
        深入敵營: 0,
        無名小鎮的無解之謎: 0,
        "ㄕㄜˊ不ㄕㄜ`": 0,
        反目成仇: 0,
        AlGoBang: 0,
        "Modern Web": 0,
    },
    第六小隊: {
        "T.E.S.T.": 0,
        深入敵營: 0,
        無名小鎮的無解之謎: 0,
        "ㄕㄜˊ不ㄕㄜ`": 0,
        反目成仇: 0,
        AlGoBang: 0,
        "Modern Web": 0,
    },
    第七小隊: {
        "T.E.S.T.": 0,
        深入敵營: 0,
        無名小鎮的無解之謎: 0,
        "ㄕㄜˊ不ㄕㄜ`": 0,
        反目成仇: 0,
        AlGoBang: 0,
        "Modern Web": 0,
    },
    第八小隊: {
        "T.E.S.T.": 0,
        深入敵營: 0,
        無名小鎮的無解之謎: 0,
        "ㄕㄜˊ不ㄕㄜ`": 0,
        反目成仇: 0,
        AlGoBang: 0,
        "Modern Web": 0,
    },
} as Record<string, Record<string, number>>);
